OneDrive - Collège de Rosemont/Automne 2023/Web 3/Projet Personnel/BoutiqueCafe/BoutiqueCafe/Controllers/CommandeController.cs
using BoutiqueCafe.Models;
using BoutiqueCafe.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BoutiqueCafe.Controllers
{
    public class CommandeController : Controller
    {
        private ICommandeRepository commandeRepository;
        private IPanierAchatRepository panierAchatRepository;
        public CommandeController(ICommandeRepository commandeRepository, IPanierAchatRepository panierAchatRepository)
        {
            this.commandeRepository = commandeRepository;
            this.panierAchatRepository = panierAchatRepository;
        }

        public IActionResult Paiement()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Paiement(Commande commande)
        {
            commandeRepository.EffectuerCommande(commande);
            panierAchatRepository.SupprimerPanier();
            HttpContext.Session.SetInt32("CartCount", 0);
            return RedirectToAction("PaiementComplete");
        }

        public IActionResult PaiementComplete()
        {
            return View();
        }
    }
}

OneDrive - Collège de Rosemont/Automne 2023/Web 3/Projet Personnel/BoutiqueCafe/BoutiqueCafe/Controllers/PanierAchatController.cs
using BoutiqueCafe.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BoutiqueCafe.Controllers
{
    public class PanierAchatController : Controller
    {
        private IPanierAchatRepository panierAchatRepository;
        private IProduitRepository produitRepository;
        public PanierAchatController(IPanierAchatRepository panierAchatRepository, IProduitRepository produitRepository)
        {
            this.panierAchatRepository = panierAchatRepository;
            this.produitRepository = produitRepository;
        }

        public IActionResult Index()
        {
            var articles = panierAchatRepository.GetPanierArticles();
            panierAchatRepository.PanierArticlesRecuperes = articles;
            ViewBag.TotalPanier = panierAchatRepository.GetPanierAchatTotal();
            return View(articles);
        }

        public RedirectToActionResult AjouterAuPanierAchat(int Id)
        {
            var produit = produitRepository.GetAllProduits().FirstOrDefault(p => p.Id == Id);
            if(produit != null)
            {
                panierAchatRepository.AjouterAuPanier(produit);
                int cartCount = panierAchatRepository.GetPanierArticles().Count;
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");

        }

        public RedirectToActionResult RetirerDuPanierAchat(int Id)
        {
            var produit = produitRepository.GetAllProduits().FirstOrDefault(p => p.Id == Id);
            if (produit != null)
            {
                panierAchatRepository.RetirerDuPanier(produit);
                int cartCount = panierAchatRepository.GetPanierArticles().Count;
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");
        }
    }
}

OneDrive - Collège de Rosemont/Automne 2023/Web 3/Projet Personnel/BoutiqueCafe/BoutiqueCafe/Controllers/ProduitController.cs
using BoutiqueCafe.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BoutiqueCafe.Controllers
{
    public class ProduitController : Controller
    {
        private IProduitRepository produitRepository;
        public ProduitController(IProduitRepository produitRepository)
        {
            this.produitRepository = produitRepository;
        }

        public IActionResult Boutique()
        {
            return View(produitRepository.GetAllProduits());
        }

        public IActionResult Detail(int id)
        {
            var produit = produitRepository.GetDetailProduit(id);
            if(produit == null)
            {
                return NotFound();
            }
            return View(produit);
        }
       
    }
}

OneDrive - Collège de Rosemont/Automne 2023/Web 3/Projet Personnel/BoutiqueCafe/BoutiqueCafe/Views/PanierAchat/Index.cshtml
@model IEnumerable<Panier>  

@if(@Model.Count() > 0){
    <section class="h-100 h-custom">
     <div class="container py-5 h-100">
         <div class="row d-flex justify-content-center align-items-center h-100">
             <div class="col-12">
                 <div class="card card-registration card-registration-2" style="border-radius: 15px; background-color:#fafafa">
                     <div class="card-body p-0">
                         <div class="row g-0">
                             <div class="col-lg-7">
                                 <div class="p-5">
                                     <div class="d-flex justify-content-between align-items-center mb-5">
                                         <h2 class="fw-bold mb-0 text-black">Panier d'achats</h2>
                                         <h6 class="mb-0 text-muted">@Model.Count() articles</h6>
                                     </div>
                                     <hr class="my-4">
                                     
                                     @foreach (var item in Model)
                                     {
                                         <div class="row mb-4 d-flex justify-content-between align-items-center">
                                            <div class="col-md-2 col-lg-2 col-xl-2">
                                                <img src="@item.Produit?.ImageUrl"
                                                     class="img-fluid rounded-3">
                                            </div>
                                            <div class="col-md-3 col-lg-3 col-xl-3">
                                                <h6 class="text-black mb-0">@item.Quantite x @item.Produit?.Nom</h6>
                                            </div>

                                            <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                <h6 class="mb-0">@(item.Quantite * item.Produit?.Prix)</h6>
                                            </div>

                                            <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                <a asp-controller="PanierAchat" asp-action="RetirerDuPanierAchat" asp-route-Id="@item.Produit?.Id" class="text-decoration-none"><h3>&#128465;</h3></a>
                                            </div>

                                        </div>

                                        <hr class="my-4">
                                    
                                        }



                                        <div class="pt-5">
                                            <h6 class="mb-0">
                                                <a asp-controller="Produit" asp-action="Boutique">
                                                    <i class="fas fa-long-arrow-alt-left me-2"></i>Retourner au magasin
                                                </a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-5 bg-grey">
                                    <div class="p-5">
                                        <h4 class="fw-bold mb-5 mt-2 pt-1">Résumé</h4>
                                        <hr class="my-4">
                                        <div class="d-flex justify-content-between mb-5">
                                            <h5 class="text-uppercase">Prix Total</h5>
                                            <h5>@ViewBag.TotalPanier.ToString("c")</h5>
                                        </div>

                                        <a asp-controller="Commande" asp-action="Paiement">
                                            <button type="button"
                                                    class="btn btn-primary w-100 text-center"
                                                    data-mdb-ripple-color="dark">
                                                Procéder à l'achat
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

else {
    <div class="container">
        <br><br><br><br>
        <div class="text-center">
            <img src="https://www.svgrepo.com/show/17356/empty-cart.svg" class="img-fluid" style="width: 200px; height: 200px; margin-left: auto; margin-right: auto" alt="...">
            <br>
            <h1><strong>Votre panier est vide</strong></h1>
            <br>
            <p>Avant de procéder au paiement, vous devez ajouter certains produits à votre panier. Vous trouverez de nombreux produits intéressants sur notre page "Boutique".</p>
            <a asp-controller="Produit" asp-action="Boutique" class="btn btn-primary w-20">
            Acheter maintenant
            </a>
            </div>
            </div>
}